on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
        with:
          repository: quarkusio/quarkus-platform
          path: quarkus-platform

      - name: Update QOSDK version to in quarkus-platform
        run: |
          cd quarkus-platform
          mvn -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=6.2.1
          ./mvnw -Dsync

      - name: Check outputs
        if: ${{ steps.qp-pr.outputs.pull-request-number }}
        run: |
            echo "Pull Request Number - ${{ steps.qp-pr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.qp-pr.outputs.pull-request-url }}"

      - name: Create quarkus-platform pull request
        uses: peter-evans/create-pull-request@v5
        id: qp-pr
        with:
          path: quarkus-platform
          title: "WIP: Ignore please"
          commit-message: "WIP: Ignore please"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{steps.metadata.outputs.current-version}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/quarkus-platform
          delete-branch: true
