on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3
        with:
          repository: operator-framework/java-operator-plugins
          path: sdk-plugins

      - name: Update QOSDK version to in java-operator-plugins
        run: |
          pwd
          cd sdk-plugins
          ls $(pwd)/pkg/quarkus/v1alpha/scaffolds/internal/templates/pomxml.go
          sed -i '' -e 's|<quarkus-sdk.version>.*</quarkus-sdk.version>|<quarkus-sdk.version>6.2.1</quarkus-sdk.version>|' $(pwd)/pkg/quarkus/v1alpha/scaffolds/internal/templates/pomxml.go
          
      - uses: actions/checkout@v3
        with:
          repository: quarkusio/quarkus-platform
          path: quarkus-platform

      - name: Update QOSDK version to in quarkus-platform
        run: |
          cd quarkus-platform
          pwd
          mvn -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=6.2.1
          ./mvnw -Dsync

      - name: Create java-operator-plugins pull request
        uses: peter-evans/create-pull-request@v5
        with:
          path: sdk-plugins
          title: "WIP: Ignore please"
          commit-message: "WIP: Ignore please"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{steps.metadata.outputs.current-version}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/java-operator-plugins

      - name: Create quarkus-platform pull request
        uses: peter-evans/create-pull-request@v5
        with:
          path: quarkus-platform
          title: "WIP: Ignore please"
          commit-message: "WIP: Ignore please"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{steps.metadata.outputs.current-version}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/quarkus-platform
